[package]
name = "monoxide"
version = "0.0.1"
edition = "2021"
homepage = "https://github.com/rami3l/monoxide"
repository = "https://github.com/rami3l/monoxide"
readme = "README.md"

[dependencies]
anyhow = "1.0.95"
kurbo = "0.11.1"
norad = { version = "0.14.2", features = ["kurbo"] }

[build-dependencies]

[lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
trivial_numeric_casts = "warn"
unused_allocation = "warn"

[lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
dbg_macro = "warn"
todo = "warn"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
wildcard_imports = "allow"

[workspace]
members = [".", "crates/monoxide-script", "crates/monoxide-ttf"]

[workspace.dependencies]
# Monoxide itself
monoxide-script = { path = "crates/monoxide-script" }
monoxide-ttf = { path = "crates/monoxide-ttf" }
monoxide = { path = "." }
# Deps
rquickjs = { version = "0.9.0", features = ["macro"] }
spiro = { git = "https://github.com/Pangpang-Studio/spiro.rlib.git", version = "1.0.2" }
num-traits = "0.2.19"
