[package]
name = "monoxide-script"
version = "0.1.0"
edition = "2021"

[dependencies]
monoxide-curves.workspace = true
monoxide-spiro.workspace = true
monoxide-ttf.workspace = true
rquickjs.workspace = true
serde.workspace = true
thiserror.workspace = true
