[package]
name = "monoxide-ttf"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.8.0"
bytes = "1.9.0"
fixed = "=1.28.0"
indexmap = "2.7.1"
rust_decimal = { version = "1.36.0", default-features = false }
thiserror = "2.0.11"
widestring = "1.1.0"
