[package]
name = "monoxide-curves"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
flo_curves.workspace = true
monoxide-spiro.workspace = true
num-traits.workspace = true
serde.workspace = true
