[package]
name = "monoxide-spiro"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
spiro-sys.workspace = true

[dev-dependencies]
insta = "1.43.2"
