[package]
name = "monoxide-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.3", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
notify = "8.0.0"
monoxide-curves.workspace = true
monoxide-script.workspace = true
# TODO: Remove this direct dependency.
rquickjs.workspace = true
glob.workspace = true
dunce.workspace = true
path-slash.workspace = true # for windows paths
axum = "0.8.3"
