[package]
name = "monoxide-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap.workspace = true
tokio = { version = "1.36.0", features = ["full"] }
notify = "8.0.0"
monoxide-curves.workspace = true
monoxide-script.workspace = true
monoxide-spiro.workspace = true
# TODO: Remove this direct dependency.
rquickjs.workspace = true
glob.workspace = true
dunce.workspace = true
path-slash.workspace = true # for windows paths
axum = { version = "0.8.3", features = ["macros", "ws"] }
tracing-subscriber.workspace = true
tracing.workspace = true
axum-reverse-proxy = "0.8.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { version = "1.0" }
tower-http = { version = "0.6", features = ["fs"] }
futures-util = { version = "0.3", default-features = false, features = [
    "sink",
    "std",
] }
