[package]
name = "monoxide-playground"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
monoxide-curves.workspace = true
monoxide-script.workspace = true
# TODO: Remove this direct dependency.
rquickjs.workspace = true
